DROP TABLE IF EXISTS GERENTE;
DROP TABLE IF EXISTS TRABALHA;
DROP TABLE IF EXISTS COMPANHIA;
DROP TABLE IF EXISTS EMPREGADO;

CREATE TABLE EMPREGADO(
	cod_empregado INT,
	nome_empregado VARCHAR(50),
	rua VARCHAR(50),
	cidade VARCHAR(50),
	salario DOUBLE PRECISION,
	PRIMARY KEY (cod_empregado)
);

CREATE TABLE COMPANHIA(
	CNPJ VARCHAR(14),
	nome_companhia VARCHAR(50),
	cidade VARCHAR(50),
	PRIMARY KEY (CNPJ)
);

CREATE TABLE TRABALHA(
	cod_empregado INT,
	CNPJ VARCHAR(14),
	FOREIGN KEY (cod_empregado) REFERENCES EMPREGADO(cod_empregado),
	FOREIGN KEY (CNPJ) REFERENCES COMPANHIA(CNPJ),
	PRIMARY KEY(cod_empregado, CNPJ)
);

CREATE TABLE GERENTE(
	cod_empregado INT,
	cod_companhia VARCHAR(14),
	FOREIGN KEY (cod_empregado) REFERENCES EMPREGADO(cod_empregado),
	FOREIGN KEY (cod_companhia) REFERENCES COMPANHIA(CNPJ),
	PRIMARY KEY (cod_empregado, cod_companhia)
);
